[package]
name = "escrow"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
solana-program = "2.0.14"
borsh = "1.5.1"
spl-token = { version = "6.0.0", features = ["no-entrypoint"]}
bytemuck = { version = "1.19.0", features = ["derive" , "const_zeroed"] }